### ISSUE TITLE
Use kraken2 as an alternative to bowtie2 to extract viral reads

### ISSUE THREAD

**Issue by ameynert** [nf-core/viralrecon#1]
I'm going to be working on polyA selected RNA-seq from people with COVID19 and plan to use the Kraken2 indexes generated here: https://genexa.ch/sars2-bioinformatics-resources/

Would like to see optionally pulling viral reads direct from mixed samples.

**Comment by drpatelh** [comment]
If possible, I think we should use `kraken2` as opposed to a `bowtie2` for the extraction of viral reads directly to fastq. It will simplify the pipeline quite a bit, seems to make more sense and will be much quicker. I am unsure of how the two will compare in terms of sensitivity but maybe we can implement and test this? 

Would also be nice if the pipeline has a process to build the `kraken2` database from the host and viral fasta if it isn't provided - although I am not sure how long this will take to build (something else worth testing) and we will need to have checks in place to make sure we aren't running offline because I think you need to download the taxonomy files beforehand 🤔

**Comment by drpatelh** [comment]
Added here https://github.com/nf-core/viralrecon/pull/16
