### ISSUE TITLE
Where do I put bowtie2-index files?

### ISSUE THREAD

**Issue by jonbra** [nf-core/viralrecon#160]
Bowtie2-build requests 16GB of memory which causes the run to crash. I can build the indexes myself, but where do I put the files so that the pipeline does not execute bowtie2-build? Alternatively, how can I customize how bowtie2-build is executed?

Thanks, Jon

**Comment by drpatelh** [comment]
Hi @jonbra! Hope you are well! Providing your own `bowtie2` indices isn't possible with v1.1.0 but it will be in the next release! Sorry, it is taking much longer than anticipated to get it out because we have been adding some cool new functionality and simplifying things substantially. Come find us on the #viralrecon channel on the [nf-core Slack](https://nf-co.re/join) workspace. Be easier to have a chat about these sorts of things and get updates.

**Comment by jonbra** [comment]
I see, thanks! (I could also fix this by reducing the --max_memory btw).
