### ISSUE TITLE
Conditional include are not expected to work 

### ISSUE THREAD

**Issue by pditommaso** [nf-core/viralrecon#201]
Don't think this pattern is a good idea, if it works it's a bug! 

https://github.com/nf-core/viralrecon/blob/a85d5969f9025409e3618d6c280ef15ce417df65/main.nf#L55-L72

**Comment by drpatelh** [comment]
It does work indeed because the CI tests each of these independently. Will need to remember why I done things this way but I suspect it was because `include` out of the conditional statement didn't give me the expected behaviour.

**Comment by drpatelh** [comment]
Yep, so the problem is that if I move the `include` out of the conditional block then the code in all of those workflows is still executed even if it isn't invoked with e.g. `ILLUMINA ()`. This messes with the parameter validation etc I have written there because these workflows have different `params` and for example I get this error when running the Illumina workflow that is actually coming from [this line](https://github.com/nf-core/viralrecon/blob/a85d5969f9025409e3618d6c280ef15ce417df65/workflows/nanopore.nf#L15) as a result of `include` the Nanopore workflow out of the conditional block:

```
ARTIC scheme not specified with e.g. --artic_scheme 'nCoV-2019' or via a detectable config file.
```

Not sure I am making sense 😅 Let me try a couple of things.

**Comment by pditommaso** [comment]
I warn you this can stop at any time, this was never meant to work in this way

**Comment by drpatelh** [comment]
I agree. If you don't think it's a good idea then we need to find a fix 🛠️ 

So I had to move that conditional logic to within the workflow's themselves and these are the minimal changes I can make to get everything working https://github.com/nf-core/viralrecon/pull/199/commits/f889766353df3ef558967016d6d564f813c4a8a2

How does that look?

**Comment by JoseEspinosa** [comment]
@pditommaso will it work if the `include` is inside a condition outside the `workflow` statement, this will then solve the problem @drpatelh mentioned above.

e.g. 

```bash
if (params.public_data_ids) {
    include { SRA_DOWNLOAD } from "${moduleDir}/workflows/sra_download"
}
else if (params.platform == 'illumina') {
    include { ILLUMINA } from "${moduleDir}/workflows/illumina.nf"
}
else {
    include { NANOPORE } from "${moduleDir}/workflows/nanopore"
}

workflow NFCORE_VIRALRECON {
    if (params.public_data_ids) {
        SRA_DOWNLOAD ()
    } else if (params.platform == 'illumina') {
        ILLUMINA ()
    } else if (params.platform == 'nanopore') {
        NANOPORE ()
    }
}
```

**Comment by pditommaso** [comment]
That should be ok, but what's the real need of condition inclusion?

**Comment by JoseEspinosa** [comment]
This 👇 
> Yep, so the problem is that if I move the `include` out of the conditional block then the code in all of those workflows is still executed even if it isn't invoked with e.g. `ILLUMINA ()`. This messes with the parameter validation etc I have written there because these workflows have different `params` and for example I get this error when running the Illumina workflow that is actually coming from [this line](https://github.com/nf-core/viralrecon/blob/a85d5969f9025409e3618d6c280ef15ce417df65/workflows/nanopore.nf#L15) as a result of `include` the Nanopore workflow out of the conditional block:
> 
> ```
> ARTIC scheme not specified with e.g. --artic_scheme 'nCoV-2019' or via a detectable config file.
> ```
> 
> Not sure I am making sense 😅 Let me try a couple of things.

**Comment by drpatelh** [comment]
Much better solution @JoseEspinosa 👍🏽 Reverted to that here https://github.com/nf-core/viralrecon/pull/199/commits/40d520e3d642a0b85fcec8609af8fd1352c132a6

**Comment by drpatelh** [comment]
Tests are happy again. Thanks for pointing this out @pditommaso :) Will remember to change this elsewhere too.

**Comment by pditommaso** [comment]
> so the problem is that if I move the include out of the conditional block then the code in all of those workflows is still executed even if it isn't invoked with e.g. ILLUMINA ().

Can you point out an example?

**Comment by drpatelh** [comment]
So both the `ILLUMINA` and `NANOPORE` workflows have their own parameter validation functions [here](https://github.com/nf-core/viralrecon/blob/a85d5969f9025409e3618d6c280ef15ce417df65/workflows/illumina.nf#L17) and [here](https://github.com/nf-core/viralrecon/blob/a85d5969f9025409e3618d6c280ef15ce417df65/workflows/nanopore.nf#L15). If we `include` both of these workflows at the same time without any conditional logic then both of those functions get executed at run-time. I would like to avoid that because the parameter validation will obviously depend on which workflow the user chooses to run.

**Comment by JoseEspinosa** [comment]
@pditommaso I modified the [example](https://github.com/JoseEspinosa/nxf_issue_conditional_include/) I added on the nextflow [issue](https://github.com/nextflow-io/nextflow/issues/2162) I opened yesterday. If you run:

```bash
nextflow run main.nf --skip_foo
```

Due to the [validation](https://github.com/JoseEspinosa/nxf_issue_conditional_include/blob/58c00c91941d3382992b2111db524c8b05c0a38d/workflows/modules/foo/main.nf#L2) trigger by the [inclusion](https://github.com/JoseEspinosa/nxf_issue_conditional_include/blob/58c00c91941d3382992b2111db524c8b05c0a38d/workflows/my_pipeline.nf#L7) of the FOO `process` you get an error. 

```bash
N E X T F L O W  ~  version 21.04.0
Launching `main.nf` [mighty_wescoff] - revision: 71cf30c291
WARN: Access to undefined parameter `foo` -- Initialise it to a default value eg. `params.foo = some_value`
Missing foo parameter
```

This is solved by putting the `include` inside a conditional statement.

**Comment by pditommaso** [comment]
I think we should introduce a `validation` concept to separate this logic from the pipeline execution

**Comment by drpatelh** [comment]
Sounds interesting. How would something like that look? Would it be something implemented in native NF or in the pipeline?

**Comment by JoseEspinosa** [comment]
Yeah, also curious 🤓
