### ISSUE TITLE
Remove replacement of dashes in sample name with underscores

### ISSUE THREAD

**Issue by peterk87** [nf-core/viralrecon#234]
## Is your feature request related to a problem? Please describe

I'd like dashes to be preserved as dashes in sample names.

## Describe the solution you'd like

Any of the following or similar solutions would be great:

- Workflow param to skip replacing dashes
- Sample name invalid characters regex workflow param (e.g. `--sample_name_invalid_chars "\W"`)
- Sample name "whitelist" regex of valid characters allowed workflow param (e.g. `--sample_name_regex "[\w\-]+"`)

## Describe alternatives you've considered

Commenting out the following code:

https://github.com/nf-core/viralrecon/blob/2ebae61442598302c64916bd5127cf23c8ab5611/bin/check_samplesheet.py#L102-L106

**Comment by drpatelh** [comment]
Hi @peterk87. I had to add this sanity re-naming because QUAST does an internal conversion of dashes to underscores which breaks the collection and reporting of the summary metrics generated by MultiQC including consensus type metrics for the variant calling. This is why it made sense to do this renaming at the offset rather than getting weird discrepancies in sample names.  It took me a while to track this down and provide a solution because it wasn't an obvious one.

Maybe we should push this issue upstream to QUAST and we can remove this conversion altogether? If you try to run one of the QUAST processes manually using dashes in the names you will see what I mean.

I am not really working at the mo and won't be until September so will try and catch up when I get a moment. PRs welcome too :)

**Comment by peterk87** [comment]
Thanks for clarifying @drpatelh!

I think pushing the issue upstream to QUAST is a great idea. I'll look into what QUAST is doing and see if the conversion can be made optional or modified.

**Comment by peterk87** [comment]
Issue created for QUAST: https://github.com/ablab/quast/issues/179

**Comment by drpatelh** [comment]
- QUAST module was updated to 5.2.0 in https://github.com/nf-core/viralrecon/pull/314/commits/f106fafb8ca4172dde46887c6ccd62028a4eb1ef 
- Dash replacement was removed from the pipeline in https://github.com/drpatelh/nf-core-viralrecon/commit/81e03d5cf5faa1a712acb1e9bb101ffeb398da5a

I have confirmed that this works as expected 🎉
