### ISSUE TITLE
Reference genomes and databases

### ISSUE THREAD

**Issue by drpatelh** [nf-core/viralrecon#3]
We will need to provide a mechanism by which users can automatically obtain the reference genomes and databases that are specific to this pipeline. It is likely that we will need the host reference as well as the viral reference sequence available. The host reference will already be available in [`igenomes.config`](https://github.com/nf-core/viralrecon/blob/dev/conf/igenomes.config) but we will need to figure out a way of uploading the viral (in this case COVID-19) sequence somewhere so it can just be pulled if not provided by the user. Once we have finalised the files/indices required for the pipeline maybe we can upload this all to AWS iGenomes?

**Comment by saramonzon** [comment]
The files needed for the pipeline are:

- Human reference genome + bowtie2 indexes.
- Virus reference genome + bowtie2 indexes + blast db + gff/gtf file (Currently NC_045512,2 version from refseq is being used for sars-cov-2)

--


)

**Comment by heuermh** [comment]
What is the best way to get the GFF/GTF file?

There is one linked here
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz

or would it be better to generate one from the NC_045512,2 full Genbank record?

**Comment by drpatelh** [comment]
Yep, it would be helpful if we can have links to where the reference files were downloaded (especially for the virus). If they have been generated manually from standard files (e.g. blast db) then worth listing the command used here too.

Also, just out of interest why did you pick NC_045512,2 as a reference sequence and not some of the others that are being used? e.g.
https://www.ncbi.nlm.nih.gov/nuccore/MN908947

I am just trying to figure out if we make all/one of these available in the format required by the pipeline?

**Comment by saramonzon** [comment]
NC_045512,2 and MN908947 are exactly the same sequences, one is the RefSeq identifier and the other one is the Genbank's. The genbank one was the one used at the beginning because the refseq didn't exist. But the sequence and coordinates are the same.

We've downloaded everything from ncbi.
Virus fasta file: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
Virus gff file:https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz

blast db:
makeblastdb -in NC_045512.2 -parse_seqids -dbtype nucl

bowtie2 index:
bowtie2-build NC_045512.2.fasta NC_045512.2.fasta

**Comment by drpatelh** [comment]
Amazing! Thanks @saramonzon. This will come in handy if and when we decide to upload the data to AWS iGenomes or I guess we could just provide URLs to the pipeline 🤔

**Comment by drpatelh** [comment]
This should be sorted now with this PR to host the viral genomes on `test-datasets`:
https://github.com/nf-core/test-datasets/pull/148
