### ISSUE TITLE
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet1.csv)'

### ISSUE THREAD

**Issue by AaronHY** [nf-core/viralrecon#309]
### Description of the bug

To whom may concern,

Thanks for such a wonderful workflow. I have tried this on my H1N1 data. There come some error regarding the Samplesheet_check. I used the suggested python script to formulate the samplesheet.csv. Please help with it. Thanks in advance.

### Command used and terminal output

```console
#Command
nextflow run nf-core/viralrecon  --input samplesheet1.csv  --outdir .  --platform illumina --protocol metagenomic  --genome 'CY121680'  -profile singularity --nextclade_dataset 'CY121680' --fasta CY121680.fasta --skip_kraken2 --kraken2_db '/mnt/e/labwork/database/kraken2_human_db.tar.gz'

# Output
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet1.csv)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-python-3.9--1.img.pulling.1651473817763 https://depot.galaxyproject.org/singularity/python:3.9--1 > /dev/null
  status : 255
  message:
    INFO:    Downloading network image
    INFO:    Cleaning up incomplete download: /home/aaronhy2022/.singularity/cache/net/tmp_2572153510
    FATAL:   unexpected EOF
```

**Comment by drpatelh** [comment]
Hi @AaronHY ! You are very welcome! 🙂 

The error is actually occuring because there is an issue pulling the Singularity images required for the pipeline.

```
Failed to pull singularity image
```

The best way to overcome this is to pre-download the Singularity images by installing the [nf-core tools](https://nf-co.re/tools/#installation) Python package and running `nf-core download`. You should then be prompted to download the images for this pipeline. I would recommend setting [`NXF_SINGULARITY_CACHEDIR`](https://www.nextflow.io/docs/latest/singularity.html?#singularity-docker-hub) to wherever you download all the images as mentioned in the main README too so you re-use these images after downloading them once.

There is an impending release this week for v2.5 so may be worth updating when that is out.
