### ISSUE TITLE
broken redirect for medaka model

### ISSUE THREAD

**Issue by alethomas** [nf-core/viralrecon#312]
### Description of the bug

when using the medaka path of the of the viralrecon pipeline an error is occuring. Seems the redirection for the file is broken (at least with curl the -L option has to be activated, to download the file). See attached log file

### Command used and terminal output

```console
nextflow run nf-core/viralrecon -qs 4 -revision 2.4.1 -profile docker --input results/benchmarking/nf-core-viralrecon/nanopore/sample-sheets/1_ont/sample_sheet.csv --sequencing_summary data/RAW/ONT_batch1/sequencing_summary.txt --fastq_dir resources/benchmarking/data/nf-core-viralrecon/1_ont/fastq_pass --fast5_dir resources/benchmarking/data/nf-core-viralrecon/1_ont/fast5_pass --platform nanopore --genome 'MN908947.3' --primer_set_version 3 --artic_minion_caller medaka --artic_minion_medaka_model r941_min_fast_g303 --outdir results/benchmarking/nf-core-viralrecon/nanopore/medaka/1_ont  > logs/nf-core-nf_core_viralrecon_nanopore/medaka/1_ont.log 2>&1
```

### Relevant files

[1_ont.log](https://github.com/nf-core/viralrecon/files/8853558/1_ont.log)

### System information

Nextflow version: 21.10.6
Hardware: Server
Executor: local via shell and Snakemake
Container engine: Docker/Conda
OS: Ubuntu 20.04.2 LTS
Version of nf-core/viralrecon: 2.4.1

**Comment by drpatelh** [comment]
Hi @alethomas ! Thanks for reporting! This appears to be an issue with the `medaka` tool attempting to auto-download the model for `r941_min_fast_g303` from the ONT servers because it may not come shipped with the particular version used by the `artic` tool. Unfortunately, I don't have any better suggestions other than trying to download the file manually and providing via `--artic_minion_medaka_model  /path/to/medaka/model`.

There are some docs [here](https://github.com/nanoporetech/medaka#models) for getting a list of models via the `medaka` tool. Once installed you should be able to run something like:

```console
$ medaka tools download_models --models r941_min_fast_g303
[13:07:50 - ResolveModels] Model r941_min_fast_g303 is stored at: /home/<TRUNCATED>/python3.8/site-packages/medaka/data/r941_min_fast_g303_model.hdf5
```

Will close this for now as there doesn't seem to be fix I can add to the pipeline for this.
