### ISSUE TITLE
ivariant filtering problem using 'tsv file' generated by 'ivar variant' command.

### ISSUE THREAD

**Issue by Moslemecoh** [nf-core/viralrecon#425]
### Description of the bug

For the variant filter, the command is given as below:
`ivar filtervariants -t 0.5 -p P.test.filtered P1_S1.tsv P2_S2.tsv P3_S3.tsv` 

But, unfortunately getting the following error message:
Header format of P1_S1.tsv did not match! Please use files generated using "ivar variants" command.
Header format of P2_S2.tsv did not match! Please use files generated using "ivar variants" command.
Header format of P3_S3.tsv did not match! Please use files generated using "ivar variants" command.

Even the header formats are unique among the files. txt files have also been used to filter but encountered the same error message. What could be the problem and solution to resolve it? Thanks in advance.
 

### Relevant files

[P1_S1.csv](https://github.com/nf-core/viralrecon/files/15074059/P1_S1.csv)
[P2_S2.csv](https://github.com/nf-core/viralrecon/files/15074060/P2_S2.csv)
[P3_S3.csv](https://github.com/nf-core/viralrecon/files/15074061/P3_S3.csv)

**Comment by mgaucoin** [comment]
I have the exact same issue. I hope someone can help. I changed the tsv format to csv so that I could upload the files here (tsv is not a supported file type).

ivar filtervariants -p $1_variants $1_A_variants.tsv $1_B_variants.tsv 
[1_A_variants.csv](https://github.com/nf-core/viralrecon/files/15178596/1_A_variants.csv)
[1_B_variants.csv](https://github.com/nf-core/viralrecon/files/15178597/1_B_variants.csv)

Header format of 1_A_variants.tsv did not match! Please use files generated using "ivar variants" command.
Header format of 1_B_variants.tsv did not match! Please use files generated using "ivar variants" command.

**Comment by Alex-Vasile** [comment]
See https://github.com/andersen-lab/ivar/issues/178

**Comment by svarona** [comment]
@Alex-Vasile @mgaucoin @Moslemecoh can we close this issue as it seems to be an ivar issue and not a viralrecon issue?

**Comment by Alex-Vasile** [comment]
> can we close this issue as it seems to be an ivar issue and not a viralrecon issue?

That depends on your philosophy of how to handle this. I could see this either being closed and wait for iVar to get fixed and let the users handle the problem. Or this package handed the problem and a workaround to be implemented into that pipeline until iVar gets fixed.

**Comment by svarona** [comment]
viralrecon generates the .vcf file of that .tsv that is correctly formatted. As viralrecon does not use `ivar filtervariants`, I think it is something that iVar should get fixed, and viralrecon users might find a way to do that filter with the .vcf using bcftools or something like that.

**Comment by Moslemecoh** [comment]
@svarona thank you for your advice and apologies for posting on a different site. Please close this issue.

**Comment by svarona** [comment]
There is nothing to apology for! Hope this helps others to get to the problem! 😄
