### ISSUE TITLE
duplicated variants in iVar path

### ISSUE THREAD

**Issue by jcurado-flomics** [nf-core/viralrecon#95]
The vcf from iVar has lines that are 100% repeated. I noticed this happens when there are overlapping features on the GFF provided. Is this normal?

If you look at the tsv files you see the difference. Here is one example for the `-profile test `run of virarecon:
```

REGION  POS     REF     ALT     REF_DP  REF_RV  REF_QUAL        ALT_DP  ALT_RV  ALT_QUAL        ALT_FREQ        TOTAL_DP        PVAL    PASS    GFF_FEATURE     REF_CODON       REF_AA  ALT_CODON
       ALT_AA

NC_045512.2     3037    C       T       0       0       0       35      7       51      1       35      1.78275e-20     TRUE    cds-YP_009724389.1      TTC     F       TTT     F
NC_045512.2     3037    C       T       0       0       0       35      7       51      1       35      1.78275e-20     TRUE    cds-YP_009725295.1      TTC     F       TTT     F
```

The only difference is the "GFF-FEATURE" field that is not present in the .vcf file.

The same behaviour is seen in the snpeff .vcf

[SAMPLE1_PE.tsv.txt](https://github.com/nf-core/viralrecon/files/4612400/SAMPLE1_PE.tsv.txt)

**Comment by drpatelh** [comment]
This should be fixed [here](https://github.com/nf-core/viralrecon/pull/96/commits/d6f01d997064552b2d6fb6ed0fe231eb38b7e194) @jcurado-flomics 

As you know, its because there may be overlapping gene features which could be impacted by any given variant. Ideally, we factor this in and output that appropriately in the `ANN` field in the VCF file much like SnpEff does for similar situations. However, given that we will be using SnpEff downstream to annotate the iVar variants anyway the fix above just checks to make sure we arent outputting duplicate variants to the VCF file.

Ill close this for now 👍

**Comment by jcurado-flomics** [comment]
Thanks! sounds good, I just wanted to know if this was normal or not :+1:
